#!/bin/bash

git pull
git commit -am "auto update"

RES=$(git show-ref --tags)
if [ -z "$RES" ]; then
    NEW_TAG=v1.0.0
else
    NEW_TAG="v$(git describe --tags --abbrev=0 | awk -F. '{OFS="."; $NF+=1; print $0}')"
fi

git tag $NEW_TAG -a "autogenerated tag"
git push origin $NEW_TAG
git push